version: '3.8'

services:
  postgresql:
    container_name: postgres-moyeo-local
    image: postgres:latest
    ports:
      - ${POSTGRES_OUTER_PORT}:${POSTGRES_INNER_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      moyeo_network:
        ipv4_address: ${NETWORK_POSTGRES_IP}
  redis:
    container_name: redis-moyeo-local
    image: redis:latest
    ports:
      - ${REDIS_OUTER_PORT}:${REDIS_INNER_PORT}
    networks:
      moyeo_network:
        ipv4_address: ${NETWORK_REDIS_IP}
networks:
  moyeo_network:
    name: moyeo_network-local
    driver: bridge
    internal: false
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          ip_range: ${NETWORK_IP_RANGE}
          gateway: ${NETWORK_GATEWAY}